# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logistics/protos/shipping_notice_item_proto/shipping_notice_item.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='logistics/protos/shipping_notice_item_proto/shipping_notice_item.proto',
  package='shipping_notice_item',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nFlogistics/protos/shipping_notice_item_proto/shipping_notice_item.proto\x12\x14shipping_notice_item\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x12ShippingNoticeItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06notice\x18\x02 \x01(\x03\x12\x11\n\tinventory\x18\x03 \x01(\x03\"\x1f\n\x1dShippingNoticeItemListRequest\"/\n!ShippingNoticeItemRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x89\x04\n\x1cShippingNoticeItemController\x12i\n\x04List\x12\x33.shipping_notice_item.ShippingNoticeItemListRequest\x1a(.shipping_notice_item.ShippingNoticeItem\"\x00\x30\x01\x12^\n\x06\x43reate\x12(.shipping_notice_item.ShippingNoticeItem\x1a(.shipping_notice_item.ShippingNoticeItem\"\x00\x12o\n\x08Retrieve\x12\x37.shipping_notice_item.ShippingNoticeItemRetrieveRequest\x1a(.shipping_notice_item.ShippingNoticeItem\"\x00\x12^\n\x06Update\x12(.shipping_notice_item.ShippingNoticeItem\x1a(.shipping_notice_item.ShippingNoticeItem\"\x00\x12M\n\x07\x44\x65stroy\x12(.shipping_notice_item.ShippingNoticeItem\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SHIPPINGNOTICEITEM = _descriptor.Descriptor(
  name='ShippingNoticeItem',
  full_name='shipping_notice_item.ShippingNoticeItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shipping_notice_item.ShippingNoticeItem.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notice', full_name='shipping_notice_item.ShippingNoticeItem.notice', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='shipping_notice_item.ShippingNoticeItem.inventory', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=192,
)


_SHIPPINGNOTICEITEMLISTREQUEST = _descriptor.Descriptor(
  name='ShippingNoticeItemListRequest',
  full_name='shipping_notice_item.ShippingNoticeItemListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=225,
)


_SHIPPINGNOTICEITEMRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ShippingNoticeItemRetrieveRequest',
  full_name='shipping_notice_item.ShippingNoticeItemRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shipping_notice_item.ShippingNoticeItemRetrieveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=274,
)

DESCRIPTOR.message_types_by_name['ShippingNoticeItem'] = _SHIPPINGNOTICEITEM
DESCRIPTOR.message_types_by_name['ShippingNoticeItemListRequest'] = _SHIPPINGNOTICEITEMLISTREQUEST
DESCRIPTOR.message_types_by_name['ShippingNoticeItemRetrieveRequest'] = _SHIPPINGNOTICEITEMRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShippingNoticeItem = _reflection.GeneratedProtocolMessageType('ShippingNoticeItem', (_message.Message,), {
  'DESCRIPTOR' : _SHIPPINGNOTICEITEM,
  '__module__' : 'logistics.protos.shipping_notice_item_proto.shipping_notice_item_pb2'
  # @@protoc_insertion_point(class_scope:shipping_notice_item.ShippingNoticeItem)
  })
_sym_db.RegisterMessage(ShippingNoticeItem)

ShippingNoticeItemListRequest = _reflection.GeneratedProtocolMessageType('ShippingNoticeItemListRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHIPPINGNOTICEITEMLISTREQUEST,
  '__module__' : 'logistics.protos.shipping_notice_item_proto.shipping_notice_item_pb2'
  # @@protoc_insertion_point(class_scope:shipping_notice_item.ShippingNoticeItemListRequest)
  })
_sym_db.RegisterMessage(ShippingNoticeItemListRequest)

ShippingNoticeItemRetrieveRequest = _reflection.GeneratedProtocolMessageType('ShippingNoticeItemRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHIPPINGNOTICEITEMRETRIEVEREQUEST,
  '__module__' : 'logistics.protos.shipping_notice_item_proto.shipping_notice_item_pb2'
  # @@protoc_insertion_point(class_scope:shipping_notice_item.ShippingNoticeItemRetrieveRequest)
  })
_sym_db.RegisterMessage(ShippingNoticeItemRetrieveRequest)



_SHIPPINGNOTICEITEMCONTROLLER = _descriptor.ServiceDescriptor(
  name='ShippingNoticeItemController',
  full_name='shipping_notice_item.ShippingNoticeItemController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=277,
  serialized_end=798,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='shipping_notice_item.ShippingNoticeItemController.List',
    index=0,
    containing_service=None,
    input_type=_SHIPPINGNOTICEITEMLISTREQUEST,
    output_type=_SHIPPINGNOTICEITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='shipping_notice_item.ShippingNoticeItemController.Create',
    index=1,
    containing_service=None,
    input_type=_SHIPPINGNOTICEITEM,
    output_type=_SHIPPINGNOTICEITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='shipping_notice_item.ShippingNoticeItemController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_SHIPPINGNOTICEITEMRETRIEVEREQUEST,
    output_type=_SHIPPINGNOTICEITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='shipping_notice_item.ShippingNoticeItemController.Update',
    index=3,
    containing_service=None,
    input_type=_SHIPPINGNOTICEITEM,
    output_type=_SHIPPINGNOTICEITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='shipping_notice_item.ShippingNoticeItemController.Destroy',
    index=4,
    containing_service=None,
    input_type=_SHIPPINGNOTICEITEM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHIPPINGNOTICEITEMCONTROLLER)

DESCRIPTOR.services_by_name['ShippingNoticeItemController'] = _SHIPPINGNOTICEITEMCONTROLLER

# @@protoc_insertion_point(module_scope)
