# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from logistics.protos.shipping_notice_proto import shipping_notice_pb2 as logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2


class ShippingNoticeControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/shipping_notice.ShippingNoticeController/List',
                request_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeListRequest.SerializeToString,
                response_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                )
        self.Create = channel.unary_unary(
                '/shipping_notice.ShippingNoticeController/Create',
                request_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
                response_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/shipping_notice.ShippingNoticeController/Retrieve',
                request_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeRetrieveRequest.SerializeToString,
                response_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                )
        self.Update = channel.unary_unary(
                '/shipping_notice.ShippingNoticeController/Update',
                request_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
                response_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/shipping_notice.ShippingNoticeController/Destroy',
                request_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ShippingNoticeControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShippingNoticeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeListRequest.FromString,
                    response_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                    response_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeRetrieveRequest.FromString,
                    response_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                    response_serializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shipping_notice.ShippingNoticeController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShippingNoticeController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/shipping_notice.ShippingNoticeController/List',
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeListRequest.SerializeToString,
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shipping_notice.ShippingNoticeController/Create',
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shipping_notice.ShippingNoticeController/Retrieve',
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNoticeRetrieveRequest.SerializeToString,
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shipping_notice.ShippingNoticeController/Update',
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shipping_notice.ShippingNoticeController/Destroy',
            logistics_dot_protos_dot_shipping__notice__proto_dot_shipping__notice__pb2.ShippingNotice.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
