# Generated by Django 4.0 on 2022-01-10 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_contact', models.CharField(max_length=13)),
                ('base_address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=6)),
                ('delivery_note', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.brand')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.logisticsorder')),
                ('received_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.receiveditem')),
            ],
        ),
        migrations.AddField(
            model_name='logisticsorder',
            name='products',
            field=models.ManyToManyField(blank=True, to='order.Product'),
        ),
        migrations.AddField(
            model_name='logisticsorder',
            name='tracking_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.courier'),
        ),
    ]
