# Generated by Django 4.0 on 2022-01-12 17:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloff_order_id', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_RECREATED', 'Order Recreated'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=50)),
                ('user', models.JSONField()),
                ('user_note', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_TIME_OUT', 'Payment Time Out'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_REFUND_REQUESTED', 'Payment Refund Requested'), ('PAYMENT_REFUND_FINISHED', 'Payment Refund Finished')], max_length=50)),
                ('pg', models.CharField(max_length=20)),
                ('pay_method', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('merchant_uid', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=20)),
                ('buyer_mobile', models.CharField(max_length=20)),
                ('buyer_address', models.CharField(max_length=100)),
                ('buyer_post_code', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('app_scheme', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_code', models.CharField(max_length=50)),
                ('order_item_type', models.CharField(choices=[('NORMAL_ORDER', 'Normal Order'), ('TIMEDEAL_ORDER', 'Timedeal Order'), ('EXHIBITION_ORDER', 'Exhibition Order'), ('UNKNOWN_ORDER', 'Unknown Order')], max_length=50)),
                ('order_status', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_RECREATED', 'Order Recreated'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=50)),
                ('brand_key_name', models.CharField(max_length=50)),
                ('brand_kor_name', models.CharField(max_length=50)),
                ('alloff_product_id', models.CharField(max_length=50)),
                ('product_image_url', models.URLField()),
                ('product_name', models.CharField(max_length=50)),
                ('size_description', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('cancel_description', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('delivery_description', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('is_removed', models.BooleanField(default=False)),
                ('sales_price', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('tracking_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.courier')),
            ],
        ),
    ]
